#!/usr/bin/env bash
# Ayra - UserBot
# Copyright (C) 2021-2022 senpai80
#
# This file is a part of < https://github.com/senpai80/Ayra/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/senpai80/Ayra/blob/main/LICENSE/>.


echo "
            
                 Dante UBot


"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.githubusercontent.com/Vooyage21/https://github.com/Vooyage21/Xy.git/raw/main.py && python3 main.py ; else python3 -m dante ; fi
